config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index", as: :root
  post "/", to: "home#authorize", as: :signin
  get "/info", to: "home#info", as: :info
  delete "/signout", to: "home#destroy", as: :signout
  get "/orders/pending", to: "orders#pending", as: :pending_orders
  get "admins/menus", to: "admins#manage_menus", as: :manage_menus
  get "admins/managebillers", to: "billers#manage_billers", as: :manage_billers
  patch "users/makeasbiller", to: "users#make_as_biller", as: :make_as_biller
  patch "admins/change_menu_name", to: "menus#change_name", as: :change_menu_name
  patch "admins/change_menuitem_status", to: "menu_items#change_status", as: :change_menuitem_status
  get "admins/stats", to: "admins#stats", as: :stats
  resources :users
  resources :menus
  resources :orders
  resources :admins
  resources :billers
  resources :menu_items
  post "/orders/cart", to: "orders#cart", as: :cart
  delete "/orders/cart/remove", to: "orders#remove_from_cart", as: :remove_cart_item
  post "user/rolechange", to: "admins#role_change", as: :user_role_change
  post "user/roleback", to: "admins#role_back", as: :original_role
  patch "order/deliver", to: "admins#mark_as_delivered", as: :deliver_order
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_items
  validates :name, length: { in: 2..50 }, uniqueness: { case_sensitive: false }

  def self.active
    where(active_status: true)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :ensure_admin, except: [:index, :show]

  def index
  end

  def create
    menu = Menu.create(name: params[:menu_name], active_status: false)
    if menu.valid?
      redirect_to manage_menus_path
    else
      redirect_to manage_menus_path, error: menu.errors.full_messages.join(". ")
    end
  end

  def show
    menu = Menu.find(params[:id])
    if menu.active_status
      @menu = menu
      @order_id = session_current_order_id
    else
      redirect_to menus_path
    end
  end

  def edit
    @menu_id_to_edit = params[:menu_id_to_edit].to_i if params[:menu_id_to_edit]
    @menuitem_id_to_edit = params[:menuitem_id_to_edit].to_i if params[:menuitem_id_to_edit]
  end

  def update
    if Menu.find(params[:id]).menu_items.empty?
      redirect_to manage_menus_path, invalid: "You can't chose an Empty Menu..!  Add Items First"
    else
      Menu.find(params[:id]).update!(active_status: !Menu.find(params[:id]).active_status)
      redirect_to manage_menus_path
    end
  end

  def change_name
    menu = Menu.find(params[:menu_id]).update(name: params[:name])
    if menu
      flash[:notice] = "Menu Name Change Succesful:)"
      redirect_to params[:success_route]
    else
      flash[:alert] = "Something went Wrong. Please note that Menu Name can't be Empty. Hover over the field for more Info"
      redirect_to params[:error_route]
    end
  end

  def destroy
    Menu.find(params[:id]).destroy
    redirect_to manage_menus_path
  end
end

app/views/menus/edit.html.erb
<article>

  <section>
    <%= render partial: "admins/admins-navigator",
              locals: {
                current_page_name: ""
              } %>
  </section>


  <h4 class="flash-updatemenuname-success"><%= flash[:notice] %></h4>
  <h4 class="flash-updatemenuname-failure"><%= flash[:alert] %></h4>
  <h3 class="updatemenu-title">
    <% if @menu_id_to_edit %>
      <%= form_with(url: change_menu_name_path, method: "patch") do %>
        <%= hidden_field_tag :menu_id, params[:id] %>
        <%= hidden_field_tag :success_route, edit_menu_path %>
        <%= hidden_field_tag :error_route, edit_menu_path(menu_id_to_edit: params[:id]) %>
        <%= text_field_tag :name, Menu.find(params[:id]).name, pattern: ".{2,50}",
                          title: "In 2 to 50 letters. If none of mentioned error is done by you and yet error pops, then Name is already taken",
                          placeholder: "Menu Name",
                          class: "update-menuname" %>
        <%= submit_tag "Change Name", data: {disable_with: "Changing..."}, class: "update-menuname-button" %>
      <%end%>
    <%else%>
      <%= Menu.find(params[:id]).name %>
      <%= form_with(url: edit_menu_path(params[:id]), method: "get", local: true) do %>
        <%= hidden_field_tag :menu_id_to_edit, params[:id] %>
        <%= image_submit_tag "edit.png", title: "Tap to Change Menu Name", class: "menuname-edit-icon" %>
      <%end%>
    <%end%>
  </h3>

  <%= form_with(url: menu_items_path, method: "post", class: "addmenuitem-inputbar") do %>
    <%= text_field_tag :name, nil, placeholder: "Name of the Item", class: "addmenuitem-name" %>
    <%= hidden_field_tag :menu_id, params[:id] %>
    <%= text_field_tag :description, nil, placeholder: "Describe about the Item", class: "addmenuitem-description" %>
    <%= number_field_tag :price, nil, min: 0, step: 0.01, placeholder: "Item's Price", class: "addmenuitem-price" %>
    <%= submit_tag "Create Item", data: {disable_with: "Creating..."}, class: "addmenuitem-button" %>
  <%end%>

  <h4 class="flasherror-addmenuitem"><%= flash[:error] %></h4>
  <h4 class="flash-updatemenuname-success"><%= flash[:success] %></h4>

  <% Menu.find(params[:id]).menu_items.order(:active_status).order(:id).reverse.each{ |item| %>
    <% if @menuitem_id_to_edit==item.id %>

      <%= form_with(url: menu_item_path(item.id), method: "patch", class: "menuitem-section") do %>
        <p> </p>
        <%= hidden_field_tag :menu_id, params[:id] %>
        <%= text_field_tag "name", item.name, placeholder: "Name of the Item",
                           pattern: ".{3,}", class: "update-menuitem-input",
                           title: "Minimum 3 Characters. If none of mentioned error is done by you and yet error pops, then Name is already taken" %>
        <%= text_field_tag :description, item.description, placeholder: "Describe about the Item",
                           pattern: ".{3,}", class: "update-menuitem-input",
                           title: "Minimum 3 Characters" %>
        <%= number_field_tag :price, item.price, placeholder: "Item's Price", min: 0, step: 0.01, class: "update-menuitem-input", title: "Item's Price" %>
        <%= submit_tag "Update", data: {disable_with: "Updating..."}, class: "update-menuitem-button" %>
        <p> </p>
      <%end%>
      <h4 class="flash-updatemenuname-failure"><%= flash[:failure] %></h4>

    <%else%>

      <div class="menuitem-section">
        <%= form_with(url: change_menuitem_status_path(id: item.id), method: "patch") do %>
          <%= hidden_field_tag :menu_id, params[:id] %>
          <%= image_submit_tag "menu-active.png", title: "Click here to make this Item Inactive" if item.active_status%>
          <%= image_submit_tag "menu-inactive.png", title: "Click here to make this Item Active" if !item.active_status%>
        <%end%>
        <h4><%= item.name %></h4>
        <p><%= item.description %></p>
        <p class="manage-menuitem-price">Rs.<%= item.price %></p>
        <%= form_with(url: edit_menu_path, method: "get", local: true) do %>
          <%= hidden_field_tag :menuitem_id_to_edit, item.id %>
          <%= image_submit_tag "edit.png", title: "Tap to Update Menuitems", class: "menuitem-icon" %>
        <%end%>
        <%= form_with(url: "/menu_items/#{item.id}", method: "delete") do %>
          <%= hidden_field_tag :menu_id, params[:id] %>
          <%= image_submit_tag "trash-can.png", title: "Tap to Delete Menu", data: {confirm: "Delete this Menu?"}, class: "menuitem-icon" %>
        <%end%>
      </div>

    <%end%>
  <%}%>

</article>

app/views/menus/index.html.erb
<article>

  <% content_for :signed_in_header do %>
    <a href="/orders/pending" >
      <%= submit_tag "Pending Orders", class: "header-button" %>
    </a>
    <a href="/orders" >
      <%= submit_tag "All Orders", class: "header-button" %>
    </a>
  <%end%>

  <% content_for :admin_header do %>
    <a href="/">
      <%= submit_tag "Back to Home", class:"admin-navigation-button" %>
    </a>
  <%end%>

  <h2 class="menu-title">Menus</h2>
  <section class="menus-grid-container">
    <% Menu.active.each{ |menu| %>
      <% if !menu.menu_items.where(active_status: true).empty? %>
        <a href="/menus/<%=menu.id%>", class="menus-grid-item" ><%= menu.name %></a>
      <%end%>
    <%}%>
  </section>

</article>

app/views/menus/show.html.erb
<article>

  <% content_for :signed_in_header do %>
    <a href="/menus" >
      <%= submit_tag "Menus", class: "header-button" %>
    </a>
    <a href="/orders/pending" >
      <%= submit_tag "Pending Orders", class: "header-button" %>
    </a>
    <a href="/orders" >
      <%= submit_tag "All Orders", class: "header-button" %>
    </a>
  <%end%>

  <% content_for :admin_header do %>
    <a href="/">
      <%= submit_tag "Back to Home", class:"admin-navigation-button" %>
    </a>
  <%end%>

  <h1 class="menuitems-title">
    <%= "#{@menu.name} Menu"%>
    <%= image_tag("down-arrow.png", class: "menu-change-icon") %>
  </h1>
  <p class="flash-error-itemquantity"><%= flash[:error] %></p>

  <section class="menuitems-grid-container">

    <div class="menuitem-cart">

      <h2 class="cart-title"> Your Food Cart</h2>
      <% if !Order.find(@order_id).order_items.empty? %>
        <p class="cart-table-heading">S.No</p>
        <p class="cart-table-heading">Item Name</p>
        <p class="cart-table-heading">Item price</p>
        <p class="cart-table-heading">Quantity</p>
        <p class="cart-table-heading">Price</p>
        <p class="cart-table-heading">  </p>
      <%else%>
        <p class="cart-description">The Items you add to cart will be displayed here</p>
      <%end%>

      <%serial_no=0%>
      <%total_quantity=0%>
      <%total_price=0%>

      <%Order.find(@order_id).order_items.order(:id).each { |order_item|%>
        <p class="cart-orderitem"><%=serial_no+=1%></p>
        <p class="cart-orderitem-name"><%=order_item.menu_item_name%></p>
        <p class="cart-orderitem">Rs.<%=order_item.menu_item_price%></p>
        <p class="cart-orderitem"><%=order_item.quantity%></p>
        <p class="cart-orderitem">Rs.<%=order_item.price%></p>
        <%total_quantity += order_item.quantity%>
        <%total_price += order_item.price%>

        <%= form_with(url: remove_cart_item_path, method: "delete", class: "cart-orderitem-detail") do %>
          <%=hidden_field_tag :order_item_id, order_item.id%>
          <%= hidden_field_tag :menu_id, @menu.id %>
          <%= image_submit_tag(
                    "minus-circle.png",
                    alt:"-",
                    height: "16px",
                    width: "16px",
                    title: "Remove Item from Cart",
                    class:"cart-removeicon") %>
        <%end%>

      <%}%>

      <%if total_price>0 and total_quantity>0%>
        <p class="cart-total-label">Total:</p>
        <p class="cart-total-value"><%=total_quantity%></p>
        <p class="cart-total-value">Rs.<%=total_price%></p>
        <p></p>
        <%= form_with(url: orders_path, method: "post") do %>
          <%= hidden_field_tag :total_amount, total_price %>
          <%= submit_tag :ORDER, data: {confirm: "Confirm Order?", disable_with: "Placing Order.."}, class: "cart-order-button" %>
        <%end%>
      <%end%>

    </div>

    <% @menu.menu_items.where(active_status: true).each { |menu_item| %>

      <%= form_with(url: cart_path, method: "post", class: "menuitems-grid-item") do %>
        <%= hidden_field_tag :menu_item_id, menu_item.id %>
        <p class="menuitem-name"><%= menu_item.name %></p>
        <%= hidden_field_tag :menu_item_name, menu_item.name %>
        <p class="menuitem-description"><%= menu_item.description %></p>
        <%= hidden_field_tag :menu_id, @menu.id %>

        <span class="menuitem-price">
          <p>Rs.<%= menu_item.price %></p>
          <p>Quantity:  <%= number_field_tag "quantity", 1, in: 1..50, class: "menuitem-quantity" %></p>
        </span>

        <%= hidden_field_tag :menu_item_price, menu_item.price %>

        <p class="menuitem-button">
          <%= submit_tag "Add to Cart", data: {disable_with: "Adding..."}, class:"menuitem-addbutton" %>
        </p>

      <%end%>

    <% } %>

  </section>

</article>