config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index", as: :root
  post "/", to: "home#authorize", as: :signin
  get "/info", to: "home#info", as: :info
  delete "/signout", to: "home#destroy", as: :signout
  get "/orders/pending", to: "orders#pending", as: :pending_orders
  get "admins/menus", to: "admins#manage_menus", as: :manage_menus
  get "admins/managebillers", to: "billers#manage_billers", as: :manage_billers
  patch "users/makeasbiller", to: "users#make_as_biller", as: :make_as_biller
  patch "admins/change_menu_name", to: "menus#change_name", as: :change_menu_name
  patch "admins/change_menuitem_status", to: "menu_items#change_status", as: :change_menuitem_status
  get "admins/stats", to: "admins#stats", as: :stats
  resources :users
  resources :menus
  resources :orders
  resources :admins
  resources :billers
  resources :menu_items
  post "/orders/cart", to: "orders#cart", as: :cart
  delete "/orders/cart/remove", to: "orders#remove_from_cart", as: :remove_cart_item
  post "user/rolechange", to: "admins#role_change", as: :user_role_change
  post "user/roleback", to: "admins#role_back", as: :original_role
  patch "order/deliver", to: "admins#mark_as_delivered", as: :deliver_order
end

app/views/admins/_admins-navigator.html.erb
<% content_for :admin_header do %>
  <a href="/">
    <%= submit_tag "Home", class:"admin-navigation-button" if !(current_page_name == "Home") %>
    <%= submit_tag "Home", class:"present-admin-navigation-button" if current_page_name == "Home"%>
  </a>
  <%= form_with(url: user_role_change_path, method: "post") do %>
    <%= submit_tag "Walk-in Customer", class:"admin-navigation-button" %>
  <%end%>
  <a href="/admins/stats">
    <%= submit_tag "Stats", class:"admin-navigation-button" if !(current_page_name == "Stats") %>
    <%= submit_tag "Stats", class:"present-admin-navigation-button" if current_page_name == "Stats" %>
  </a>
  <a href="/admins/managebillers">
    <%= submit_tag "Manage Billers", class:"admin-navigation-button" if !(current_page_name == "Manage Billers") %>
    <%= submit_tag "Manage Billers", class:"present-admin-navigation-button" if current_page_name == "Manage Billers" %>
  </a>
  <a href="/users">
    <%= submit_tag "Users", class:"admin-navigation-button" if !(current_page_name == "Users") %>
    <%= submit_tag "Users", class:"present-admin-navigation-button" if current_page_name == "Users" %>
  </a>
  <a href="/admins/menus">
    <%= submit_tag "Manage Menus", class:"admin-navigation-button" if !(current_page_name == "Manage Menus") %>
    <%= submit_tag "Manage Menus", class:"present-admin-navigation-button" if current_page_name == "Manage Menus" %>
  </a>
  <a href="/menus">
    <%= submit_tag "Order for You", class:"admin-navigation-button" %>
  </a>
<% end %>

app/views/admins/index.html.erb
<article>

  <section>
    <%= render partial: "admins/admins-navigator",
              locals: {
                current_page_name: "Home"
              } %>
  </section>

  <% if @orders.empty? %>
     <h1 class="no-orders-title">No Pending Orders :)</h1>
  <%else%>
    <h1 class="orders-title">All Pending Orders</h1>
    <%= render partial: "orders/generate-invoice",
              locals: {
                orders: @orders.order(:placed_at),
                role: "admin"
              } %>
  <%end%>

</article>

app/views/admins/manage_menus.html.erb
<article>

  <section>
    <%= render partial: "admins/admins-navigator",
              locals: {
                current_page_name: "Manage Menus"
              } %>
  </section>

  <h2 class="manage-menus-title">Manage Menus</h2>

  <%= form_with(url: menus_path, method: "post", class: "addmenu") do %>
    <%= text_field_tag :menu_name, nil, placeholder: "Type a Menu name you want to add", class: "addmenu-inputbar" %>
    <%= submit_tag "Create Menu", data: {disable_with: "Creating..."}, class: "addmenu-button" %>
  <%end%>

  <h4 class="managemenus-flash-error"><%= flash[:error] %></h4>
  <h4 class="managemenus-flash-error"><%= flash[:invalid] %></h4>
  <h4 class="flash-updatemenuname-success"><%= flash[:notice] %></h4>

  <% Menu.order(:id).each { |menu| %>
    <% if @menu_id_to_edit==menu.id %>

      <%= form_with(url: change_menu_name_path, method: "patch", class: "menu-details") do %>
        <p> </p>
        <%= hidden_field_tag :menu_id, menu.id %>
        <%= hidden_field_tag :success_route, manage_menus_path %>
        <%= hidden_field_tag :error_route, manage_menus_path(menu_id_to_edit: menu.id) %>
        <%= text_field_tag :name, menu.name, pattern: ".{2,50}",
                           title: "In 2 to 50 letters. If none of mentioned error is done by you and yet error pops, then Name is already taken",
                           placeholder: "Menu Name",
                           class: "update-menuname" %>
        <%= submit_tag "Change Name", data: {disable_with: "Changing..."}, class: "update-menuname-button" %>
        <p> </p>
        <p> </p>
      <%end%>
      <h4 class="flash-updatemenuname-failure"><%= flash[:alert] %></h4>

    <%else%>

      <div class="menu-details">
        <%= form_with(url: "/menus/#{menu.id}", method: "patch") do %>
          <%= image_submit_tag "menu-active.png", title: "Click here to make this Menu Inactive" if menu.active_status%>
          <%= image_submit_tag "menu-inactive.png", title: "Click here to make this Menu Active" if !menu.active_status%>
        <%end%>
        <%= form_with(url: manage_menus_path, method: "get", local: true, class: "menu-name") do %>
          <%= menu.name %>
          <%= hidden_field_tag :menu_id_to_edit, menu.id %>
          <%= image_submit_tag "edit.png", title: "Tap to Change Menu Name", class: "menu-icon" %>
        <%end%>
        <%= submit_tag :Active, disabled: true, class: "menu-true-status" if menu.active_status%>
        <%= submit_tag :InActive, disabled: true, class: "menu-false-status" if !menu.active_status%>
        <%= link_to("/menus/#{menu.id}/edit") do %>
          <%= image_submit_tag "plus.png", title: "Tap to Update Menu", class: "menu-icon" %>
        <%end%>
        <%= form_with(url: "/menus/#{menu.id}", method: "delete") do %>
          <%= image_submit_tag "trash-can.png", title: "Tap to Delete Menu", data: {confirm: "Delete this Menu?"}, class: "menu-icon" %>
        <%end%>
      </div>

    <%end%>
  <%}%>

</article>

app/views/admins/stats.html.erb
<article>

  <section>
    <%= render partial: "admins/admins-navigator",
              locals: {
                current_page_name: "Stats"
              } %>
  </section>

  <%= form_with(url: stats_path, method: "get", local: true, class:"stats-filter-bar") do %>
    <%= label_tag :from_date, "From Date: ", class: "stats-filter-label" %>
    <%= date_field_tag :from_date, @from_date, class: "stats-filter-input" %>
    <%= label_tag :to_date, "To Date: ", class: "stats-filter-label" %>
    <%= date_field_tag :to_date, @to_date, class: "stats-filter-input" %>
    <%= label_tag :username, "User Name: ", class: "stats-filter-label" %>
    <%= text_field_tag :username, @username, placeholder: "Name of User to fetch Reports", class: "stats-filter-input" %>
    <%= submit_tag "Apply Filter", data: {disable_with: "Fetching..."}, class: "stats-filter-button" %>
  <%end%>
  <h4 class="flasherror-stat-username"><%= flash[:error] %><h4>

  <h3 class="stats-title">Invoices</h3>

  <section>
    <% if @invoices.empty? %>
      <p class="stat-noinvoice-msg">No Invoice found for Applied Filter:(</p>
    <%else%>
      <% @invoices.order(placed_at: :desc).each { |invoice| %>
        <%= form_with(url: order_path(id: invoice.id), method: "get", local: true, class: "stat-invoice") do %>
          <%= image_submit_tag "ok-certification.png", height: "28px", width: "28px", title: "Order Delivered", disabled: true if invoice.delivered_at%>
          <%= image_submit_tag "menu-inactive.png", height: "28px", width: "28px", title: "Order Delivery Pending", disabled: true if !invoice.delivered_at%>
          <% role = invoice.user.role %>
          <p>ID: <%= invoice.id %></p>
          <p>
            Name: <%= invoice.user.name if role=="customer"%>
            <%= "#{invoice.user.name} (Clerk)" if role=="clerk"%>
            <%= "#{invoice.user.name} (Admin)" if role=="admin"%>
          </p>
          <p>Total: Rs.<%= invoice.total_amount %></p>
          <%= image_submit_tag "right-arrow.png", title: "Click to view Full Detail", class: "stat-getinvoicedetails" %>
        <%end%>
      <%}%>
    <%end%>
  </section>

</article>