config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index", as: :root
  post "/", to: "home#authorize", as: :signin
  get "/info", to: "home#info", as: :info
  delete "/signout", to: "home#destroy", as: :signout
  get "/orders/pending", to: "orders#pending", as: :pending_orders
  get "admins/menus", to: "admins#manage_menus", as: :manage_menus
  get "admins/managebillers", to: "billers#manage_billers", as: :manage_billers
  patch "users/makeasbiller", to: "users#make_as_biller", as: :make_as_biller
  patch "admins/change_menu_name", to: "menus#change_name", as: :change_menu_name
  patch "admins/change_menuitem_status", to: "menu_items#change_status", as: :change_menuitem_status
  get "admins/stats", to: "admins#stats", as: :stats
  resources :users
  resources :menus
  resources :orders
  resources :admins
  resources :billers
  resources :menu_items
  post "/orders/cart", to: "orders#cart", as: :cart
  delete "/orders/cart/remove", to: "orders#remove_from_cart", as: :remove_cart_item
  post "user/rolechange", to: "admins#role_change", as: :user_role_change
  post "user/roleback", to: "admins#role_back", as: :original_role
  patch "order/deliver", to: "admins#mark_as_delivered", as: :deliver_order
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_secure_password
  validates :name, :email, presence: true, uniqueness: { case_sensitive: false }
  validates :address, :phone_no, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in
  before_action :ensure_admin, except: [:create, :new]

  def index
    @user_id_to_edit = nil
    @user_id_to_edit = params[:user_id_to_edit].to_i if params[:user_id_to_edit]
    if params[:username]
      @user = User.find_by(name: params[:username])
      if !@user
        flash.now[:alert] = "User not Found! Enter correct name"
      end
    end
  end

  def create
    if !(params[:password_digest] == params[:password_confirmation_digest])
      flash[:error] = "Password Mismatch.\n You must enter same content in both password fields"
      redirect_to new_user_path if params[:role] == "customer"
      redirect_to new_biller_path if params[:role] == "clerk"
    else
      user = User.create(name: params[:name],
                         role: params[:role],
                         password: params[:password_digest],
                         email: params[:email],
                         password_confirmation: params[:password_confirmation_digest],
                         address: params[:address],
                         phone_no: params[:phone_no])
      if user.valid?
        if user.role == "customer"
          order = Order.create!(user_id: user.id)
          session[:current_user_id] = user.id
          session[:current_order_id] = order.id
          redirect_to root_path
        elsif user.role == "clerk"
          redirect_to manage_billers_path
        end
      else
        flash[:error] = user.errors.full_messages.join(". ")
        redirect_to new_user_path if params[:role] == "customer"
        redirect_to new_biller_path if params[:role] == "clerk"
      end
    end
  end

  def new
    if user = current_user
      redirect_to root_path
    end
  end

  def make_as_biller
    user = User.find(params[:user_id])
    if user.role == "customer"
      user.update!(role: "clerk") if user.name != "Walk-in Customer"
    elsif user.role == "clerk"
      user.update!(role: "customer")
    end
    redirect_to params[:redirect_path]
  end

  def destroy
    User.find(params[:id]).orders.destroy_all
    User.find(params[:id]).destroy
    redirect_to params[:redirect_path]
  end
end

app/views/users/_create_user.html.erb
<%= form_with(url: users_path, method: "post", class:"signing-section") do %>
  <%= label_tag :name, "Name:", class:"signing-field-label"%><br>
  <%= text_field_tag :name,
                      nil,
                      placeholder: "How you want to be called?",
                      pattern: ".{2,}",
                      title: "Minimum 2 characters",
                      class: "signing-inputbar"
  %><br><br>
  <%= label_tag :email, "E-mail:", class:"signing-field-label"%><br>
  <%= text_field_tag "email",
                      nil,
                      placeholder: "Your valid email Id",
                      pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$",
                      title: "Expected Pattern: yyy@yyy.yy",
                      class: "signing-inputbar"
  %><br><br>
  <%= label_tag :address, "Address:", class:"signing-field-label"%><br>
  <%= text_field_tag "address",
                      nil,
                      placeholder: "Where should we deliver you?",
                      pattern: ".{10,150}",
                      title: "In 10 to 150 characters",
                      class: "signing-inputbar"
  %><br><br>
  <%= label_tag :phone_no, "Phone Number:", class:"signing-field-label"%><br>
  <%= text_field_tag "phone_no",
                      nil,
                      placeholder: "Enter your valid Contact Number",
                      pattern: "[0-9.+-].{9,50}",
                      title: "To add multiple contact numbers use ', ' in between",
                      class: "signing-inputbar"
  %><br><br>
  <%= hidden_field_tag :role, role %>
  <%= label_tag :password_digest, "Password:", class:"signing-field-label"%><br>
  <%= password_field_tag :password_digest,
                          nil,
                          placeholder: "Make your Password",
                          pattern: ".{6,12}",
                          title: "In 6 to 12 characters. It's advisable to use random passwords rather than easily guessable personal details like name, DOB, etc..",
                          class: "signing-inputbar"
  %><br><br>
  <%= label_tag :password_confirmation_digest, "Confirm Password:", class:"signing-field-label"%><br>
  <%= password_field_tag :password_confirmation_digest,
                          nil,
                          placeholder: "Confirm Your Password",
                          pattern: ".{6,12}",
                          title: "Enter same combination that you entered in 'Password' field",
                          class: "signing-inputbar"
  %>
  <p class="flash-error"><%= flash[:error] %></p>
  <p class="flash-error"><%= flash[:invalid] %></p>
  <%= submit_tag button_text, data: {disable_with: "Creating...."}, class: "signing-button" %>
<% end %>

app/views/users/_search_user.html.erb
<%= form_with(url: submit_path, method: "get", local: true, class: "user-search-bar") do %>
  <%= text_field_tag :username,
                      nil,
                      placeholder: "User Name to be Searched",
                      class: "user-search-input"
  %>
  <% if user||flash[:alert] %>
    <a href=<%=submit_path%> >
      <%= image_submit_tag "close.png", title: "Clear Search", alt: "Cancel Search", class: "cancel-search"%>
    </a>
  <%end%>
  <%= submit_tag :Search, data: {disable_with: "Searching..."}, class: "user-search-button" %>
  <a href="/billers/new">
    <%= submit_tag "Make New Biller", class: "make-biller-button" if submit_path == manage_billers_path %>
  </a>
<% end %>


<% if user %>
  <%= render partial: "users/user_details",
            locals: {
              title: "",
              role: user.role,
              name: user.name,
              redirect_path: submit_path,
              user_id_to_edit: user_id_to_edit,
              in_manage_billers_page: true
            } %>
<%end%>

app/views/users/_user_details.html.erb
<% count = 0 %>
<% loop_count = 0 %>
<h2 class="list-users-title">
  <%= title %>
  <a href="/billers/new">
    <%= image_submit_tag "plus.png", title: "Add/Make New Biller", class: "list-users-add-biller-icon" if role=="clerk" && in_manage_billers_page && !name%>
  </a>
  <a href="/admins/managebillers">
    <%= submit_tag "Manage", class: "list-users-manage-biller-button" if role=="clerk" && !in_manage_billers_page %>
  </a>
</h2>


<% User.order(:id).where("role = ?", role).each do |user| %>
<% loop_count+=1 if name %>
<% user = User.find_by("name = ?", name) if name %>
  <% if loop_count<=1 %>
    <%if user_id_to_edit==user.id%>
      <div>
        <%= form_with(url: "/billers/#{user.id}", method: "patch", class: "list-users-details") do %>
          <%count+=1%>
          <%= hidden_field_tag :redirect_path, redirect_path %>
          <p><%= text_field_tag :name, user.name,
                                placeholder: "User's Name",
                                class: "updateuser-field",
                                title: "Name. If all instructions given in flash messages are followed and yet error pops, Username is already taken" %></p>
          <p><%= text_field_tag :address, user.address,
                                placeholder: "User's Address",
                                pattern: ".{9,}", class: "updateuser-field",
                                title: "Address. Minimum 10 characters" %></p>
          <p><%= text_field_tag :email, user.email,
                                placeholder: "User's email",
                                class: "updateuser-field",
                                title: "Email. If all instructions given in flash messages are followed and yet error pops, Email-id is already taken" %></p>
          <p><%= text_field_tag :phone_no, user.phone_no,
                                placeholder: "User's Phone Number",
                                pattern: ".{10,}", class: "updateuser-field",
                                title: "Enter valid Contact Detail" %></p>
          <%= submit_tag "Update", data: {disable_with: "Updating..."}, class: "updateuser-button" %>
        <%end%>
      </div>
    <%else%>
      <div class="list-users-details">
        <p><%= "#{count += 1}. #{user.name}" if !name%><%= "#{user.name} (#{user.role.capitalize})" if name%></p>
        <p><%= user.address %></p>
        <p><%= user.email %></p>
        <%= form_with(url: make_as_biller_path(redirect_path: redirect_path), method: "patch", class: "searchuser-data-icon-merge") do %>
            <%= user.phone_no %>
            <%= hidden_field_tag :user_id, user.id %>
            <%= image_submit_tag "swap.png", height: "24px", width: "35px", data: {confirm: "Change User to Biller?"}, title: "Change role to Biller" if user.role=="customer" && user.name!="Walk-in Customer" %>
            <%= image_submit_tag "swap.png", height: "24px", width: "35px", data: {confirm: "Change User to Customer?"}, title: "Change role to Customer" if user.role=="clerk" %>
        <%end%>
        <%= form_with(url: redirect_path, method: "get", local: true, class: "list-users-updateicon") do %>
          <%= hidden_field_tag :user_id_to_edit, user.id %>
          <%= hidden_field_tag :username, user.name if name %>
          <%= image_submit_tag "edit.png", height: "22px", width: "22px", title: "Edit User Details" if !(role=="customer") %>
        <%end%>
        <%= form_with(url: user_path(user.id, redirect_path: redirect_path), method: "delete", data: {confirm: "Deleting this User will delete all orders related to that user \nAre u sure to Proceed? "}, class: "list-users-updateicon") do %>
          <%= image_submit_tag "trash-can-outline.png", height: "22px", width: "22px", title: "Delete User" if !(role=="admin")%>
        <%end%>
      </div>
    <%end%>
  <%end%>
<%end%>

app/views/users/index.html.erb
<article>

  <section>
    <%= render partial: "admins/admins-navigator",
              locals: {
                current_page_name: "Users"
              } %>
  </section>

  <section>
    <%= render partial: "users/search_user",
              locals: {
                submit_path: users_path,
                user_id_to_edit: @user_id_to_edit,
                user: @user
              }%>
      <h3 class="flash-nouser"><%= flash[:alert] %></h3>
      <hr/>
    </section>

  <section class="list-users-section">

    <h3 class="flash-updateuser-failure"><%= flash[:invalid] %></h3>
    <h3 class="flash-updateuser-success"><%= flash[:notice] %></h3>

    <%= render partial: "user_details",
              locals: {
                title: "Owner",
                role: "admin",
                name: nil,
                redirect_path: users_path,
                user_id_to_edit: @user_id_to_edit,
                in_manage_billers_page: false
              } %>
    <%= render partial: "user_details",
              locals: {
                title: "Biller",
                role: "clerk",
                name: nil,
                redirect_path: users_path,
                user_id_to_edit: @user_id_to_edit,
                in_manage_billers_page: false
              } %>
    <%= render partial: "user_details",
              locals: {
                title: "Customer",
                role: "customer",
                name: nil,
                redirect_path: users_path,
                user_id_to_edit: nil,
                in_manage_billers_page: false
              } %>

  </section>

</article>

app/views/users/new.html.erb
<article class="signup-page">

  <% content_for :header_options do %>

    <section class="additional-header-content">
      <a href="/" >
        <%= submit_tag "Sign In", class: "header-button" %>
      </a>
      <a href="/info" >
        <%= submit_tag "About Us", class: "header-button" %>
      </a>
    </section>

  <% end %>

  <h2 class="signing-page-heading">User Sign Up Form</h2>
  <%= render partial: "users/create_user",
             locals: {
               role: "customer",
               button_text: "SIGN UP"
             } %>

</article>