config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index", as: :root
  post "/", to: "home#authorize", as: :signin
  get "/info", to: "home#info", as: :info
  delete "/signout", to: "home#destroy", as: :signout
  get "/orders/pending", to: "orders#pending", as: :pending_orders
  get "admins/menus", to: "admins#manage_menus", as: :manage_menus
  get "admins/managebillers", to: "billers#manage_billers", as: :manage_billers
  patch "users/makeasbiller", to: "users#make_as_biller", as: :make_as_biller
  patch "admins/change_menu_name", to: "menus#change_name", as: :change_menu_name
  patch "admins/change_menuitem_status", to: "menu_items#change_status", as: :change_menuitem_status
  get "admins/stats", to: "admins#stats", as: :stats
  resources :users
  resources :menus
  resources :orders
  resources :admins
  resources :billers
  resources :menu_items
  post "/orders/cart", to: "orders#cart", as: :cart
  delete "/orders/cart/remove", to: "orders#remove_from_cart", as: :remove_cart_item
  post "user/rolechange", to: "admins#role_change", as: :user_role_change
  post "user/roleback", to: "admins#role_back", as: :original_role
  patch "order/deliver", to: "admins#mark_as_delivered", as: :deliver_order
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in, except: [:destroy]

  def index
    if user = current_user
      redirect_to menus_path if user.role == "customer"
      redirect_to "/billers" if user.role == "clerk"
      redirect_to "/admins" if user.role == "admin"
    end
  end

  def authorize
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password_digest])
      if user.role == "admin" || user.role == "clerk"
        walkin_order = Order.create!(user_id: User.find_by(name: "Walk-in Customer").id)
        session[:walkin_order_id] = walkin_order.id
        order = Order.create!(user_id: user.id)
      else
        order = Order.create!(user_id: user.id)
      end
      session[:current_user_id] = user.id
      session[:current_order_id] = order.id
      session[:original_user_id] = nil
      session[:original_order_id] = nil
      redirect_to "/"
    else
      redirect_to root_path, error: "Credentials doesn't Match. Try again!"
    end
  end

  def info
  end

  def destroy
    Order.find(session_current_order_id).order_items.destroy_all
    Order.find(session_current_order_id).destroy
    if session_original_order_id
      Order.find(session_original_order_id).order_items.destroy_all
      Order.find(session_original_order_id).destroy
    end
    if session_walkin_order_id
      Order.find(session_walkin_order_id).order_items.destroy_all
      Order.find(session_walkin_order_id).destroy
    end
    reset_session
    @current_user = nil
    @original_user = nil
    redirect_to root_path
  end
end

app/views/home/index.html.erb
<article class="home-page">

  <% content_for :header_options do %>

    <section class="additional-header-content">
      <a href="/users/new" >
        <%= submit_tag "Sign Up", class: "header-button" %>
      </a>
      <a href="/info" >
        <%= submit_tag "About Us", class: "header-button" %>
      </a>
    </section>

  <% end %>

  <%= form_with(url: signin_path, method: "post", class:"signing-section") do %>
    <%= label_tag :email, "E-mail:", class:"signing-field-label"%><br>
    <%= text_field_tag "email",
                       nil,
                       placeholder: "Your Registered email Id",
                       pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$",
                       title: "Expected Pattern: yyy@yyy.yy",
                       class: "signing-inputbar"
    %><br><br>
    <%= label_tag :password_digest, "Password:", class:"signing-field-label"%><br>
    <%= password_field_tag :password_digest,
                           nil,
                           placeholder: "Your Password",
                           pattern: ".{6,12}",
                           title: "6 to 12 characters",
                           class: "signing-inputbar"
    %><br><br>
    <p class="flash-error"><%= flash[:error] %></p>
    <%= submit_tag "SIGN IN", data: {disable_with: "Checking...."}, class: "signing-button" %>
  <% end %>
  <p class="alternate-signing-field">New User..? --> <%= link_to "Sign Up!", new_user_path %>

</article>

app/views/home/info.html.erb
<article>

  <% content_for :header_options do %>

    <section class="additional-header-content">
          <a href="/" >
            <%= submit_tag "Sign In", class: "header-button" %>
          </a>
          <a href="/users/new" >
            <%= submit_tag "Sign Up", class: "header-button" %>
          </a>
    </section>

  <%end%>

  <h1 class="about-me">Will be Updated Soon...</h1>

</article>